### ISSUE TITLE
run_scripting cmd can't mute the pinger effectively

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#124]
When we run the routine script, we should generically mute the pinger on the esr for the next one hour via something like:
```yaml
- action: cmd
  cmds:
    - endpoint: pinger
      method_name: silence_ping
      value: [datetime.datetime.utcnow()+datetime.timedelta(0,3600)).strftime(constants.TIME_FORMAT)]
      timeout: 100
```

Fixing this is a two part-issue:
- run_scripting's `action_cmd` doesn't try asteval logic, so this would fail.
  - asteval string processing should probably be generically implemented as a separate method, rather than specifically implemented separately in `action_set`, etc.
- asteval explicitly blocks `import` and doesn't import datetime, so the generic asteval can't accomplish this anyway
  - we could fork our own version of asteval to add the datetime functions
