### ISSUE TITLE
daq_targets, daq_configs in run_scripting

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#148]
There is a naming scheme problem in the run_scripting:
- when using single run, the user should define a list:
```
daq_configs:
     - daq_1
     - daq_2
```
- when using a multirun, the user can define a list:
```
daq_targets:
     - daq_1
     - daq_2
```
or a dictionary
```
daq_configs:
     - daq_target: daq_1
        run_duration: 1000
     - daq_target: daq_2
        run_duration: 100
```

See the problem?
It's a complete mess!
We need to clean this and make it consistent...
