### ISSUE TITLE
sleep and tmux

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#63]
For some weird reasons, when two people are connected to the same tmux session and a sleep is under way, one detaching from the session might end the sleep loop.
This might need to be investigated.

**Comment by laroque** [comment]
I've tried and failed to reproduce this in two ways. In both cases I started the job, during a sleep call I detached and attached to find things continuing to execute normally. I then attached a second terminal and tried detaching/attaching both the original and the new tty, as well as logging in from another machine and attaching/detaching. I the ssh connection was from a mac while the local was debian jessie so this should look very similar to what is going on in lab.

Is there a reliable way to reproduce this problem? Ideally one that doesn't have to include interacting with the production system.

1) The following python script run in tmux
```python
import time
import datetime

f = open('/tmp/afile.txt','w')

f.write(str(datetime.datetime.now()))
f.flush()

time.sleep(600)

f.write(str(datetime.datetime.now()))
f.flush()
```  
2) Created the follow execution script run with `dragonfly execute script.yaml`
```yaml
- action: pause_for_user
  message: "waiting to sleep 60"
- action: sleep
  duration: 60
- action: pause_for_user
  message: "waiting to sleep 61"
- action: sleep
  duration: 61
- action: pause_for_user
  message: "waiting to sleep 62"
- action: sleep
  duration: 62
```
