### ISSUE TITLE
set_and_check broken for scientific notation floats

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#66]
The check functionality is not properly parsing scientific notation floats.  Example that breaks:

```
  - name: rsa_default_config
    module: MultiDo
    targets:
      - target: rsa_central_frequency
        payload_field: value_raw
        units: Hz
        default_set: 1140E+6
```

The output said it was comparing 1140E+6 with 1140000000.0 and found them not equal, so something is not being cast correctly.  A similar (or identical?) problem was noticed in the run_scripting.
